import Link from 'next/link';

export default function Home() {
  return (
    <main className="min-h-screen bg-gradient-to-b from-blue-50 to-white">
      {/* Hero Section */}
      <div className="flex flex-col items-center justify-center px-6 py-24">
        <div className="text-center max-w-4xl">
          <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6">
            AI Tutor Mauritius 🇲🇺
          </h1>
          <p className="text-xl md:text-2xl text-gray-600 mb-8">
            Free AI-powered tutoring for secondary school students
          </p>
          <p className="text-lg text-gray-700 mb-12 max-w-2xl mx-auto">
            Access quality Computer Science education with AI-generated lessons,
            practice questions, and personalized learning - completely free.
          </p>

          {/* CTA Buttons */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/auth/register"
              className="px-8 py-4 bg-indigo-600 text-white text-lg font-semibold rounded-lg hover:bg-indigo-700 transition-colors shadow-lg"
            >
              Get Started Free →
            </Link>
            <Link
              href="/auth/login"
              className="px-8 py-4 bg-white text-indigo-600 text-lg font-semibold rounded-lg hover:bg-gray-50 transition-colors border-2 border-indigo-600"
            >
              Sign In
            </Link>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div className="max-w-6xl mx-auto px-6 py-16">
        <h2 className="text-3xl font-bold text-center text-gray-900 mb-12">
          What We Offer
        </h2>
        <div className="grid md:grid-cols-3 gap-8">
          {/* Feature 1 */}
          <div className="bg-white rounded-lg shadow-md p-6">
            <div className="text-4xl mb-4">🎓</div>
            <h3 className="text-xl font-semibold text-gray-900 mb-2">
              AI-Generated Lessons
            </h3>
            <p className="text-gray-600">
              Comprehensive lessons tailored to the Mauritius curriculum,
              generated by advanced AI technology.
            </p>
          </div>

          {/* Feature 2 */}
          <div className="bg-white rounded-lg shadow-md p-6">
            <div className="text-4xl mb-4">📝</div>
            <h3 className="text-xl font-semibold text-gray-900 mb-2">
              Practice Questions
            </h3>
            <p className="text-gray-600">
              Test your understanding with practice questions and detailed
              answers for every topic.
            </p>
          </div>

          {/* Feature 3 */}
          <div className="bg-white rounded-lg shadow-md p-6">
            <div className="text-4xl mb-4">📊</div>
            <h3 className="text-xl font-semibold text-gray-900 mb-2">
              Track Progress
            </h3>
            <p className="text-gray-600">
              Monitor your learning journey and see your improvement over time.
            </p>
          </div>
        </div>
      </div>

      {/* Curriculum Coverage */}
      <div className="bg-indigo-50 py-16">
        <div className="max-w-6xl mx-auto px-6">
          <h2 className="text-3xl font-bold text-center text-gray-900 mb-8">
            Curriculum Coverage
          </h2>
          <div className="bg-white rounded-lg shadow-md p-8">
            <div className="grid md:grid-cols-2 gap-6">
              <div>
                <h3 className="text-xl font-semibold text-gray-900 mb-3">
                  Grades Covered
                </h3>
                <p className="text-gray-700">
                  Grade 7 through Form 5 (Grade 11)
                </p>
              </div>
              <div>
                <h3 className="text-xl font-semibold text-gray-900 mb-3">
                  Subject
                </h3>
                <p className="text-gray-700">
                  Computer Science (more subjects coming soon)
                </p>
              </div>
              <div>
                <h3 className="text-xl font-semibold text-gray-900 mb-3">
                  Topics Covered
                </h3>
                <ul className="text-gray-700 space-y-1">
                  <li>• Data Representation</li>
                  <li>• Programming Fundamentals</li>
                  <li>• Databases & SQL</li>
                  <li>• And many more...</li>
                </ul>
              </div>
              <div>
                <h3 className="text-xl font-semibold text-gray-900 mb-3">
                  Total Lessons
                </h3>
                <p className="text-gray-700">
                  88 subtopics with comprehensive coverage
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-8">
        <div className="max-w-6xl mx-auto px-6 text-center">
          <p className="text-gray-400">
            Built with ❤️ for students in Mauritius
          </p>
          <p className="text-gray-500 text-sm mt-2">
            Powered by Google Gemini AI
          </p>
        </div>
      </footer>
    </main>
  );
}
